# notebook

In [3]:
import pandas as pd
df=pd.read_csv("shopping_trends.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer ID               3900 non-null   int64
 1   Age                       3900 non-null   int64
 2   Gender                    3900 non-null   object
 3   Item Purchased            3900 non-null   object
 4   Category                  3900 non-null   object
 5   Purchase Amount (USD)     3900 non-null   int64
 6   Location                  3900 non-null   object
 7   Size                      3900 non-null   object
 8   Color                     3900 non-null   object
 9   Season                    3900 non-null   object
 10  Review Rating             3900 non-null   float64
 11  Subscription Status       3900 non-null   object
 12  Payment Method            3900 non-null   object
 13  Shipping Type             3900 non-null   object
 14  Discount Applied          3900 non-null   object
 15  Promo Code Used           3900 non-null   object
 16  Previous Purchases        3900 non-null   int64
 17  Preferred Payment Method  3900 non-null   object
 18  Frequency of Purchases    3900 non-null   object
dtypes: float64(1), int64(4), object(14)
memory usage: 579.0+ KB

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [9]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Preferred Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Credit Card,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,696,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [13]:
df.isnull().sum()

customer_id                 0
age                         0
gender                      0
item_purchased              0
category                    0
purchase_amount_(usd)       0
location                    0
size                        0
color                       0
season                      0
review_rating               0
subscription_status         0
payment_method              0
shipping_type               0
discount_applied            0
promo_code_used             0
previous_purchases          0
preferred_payment_method    0
frequency_of_purchases      0
dtype: int64

In [12]:
df.columns= df.columns.str.lower().str.replace(' ', '_')

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'payment_method',
       'shipping_type', 'discount_applied', 'promo_code_used',
       'previous_purchases', 'preferred_payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [15]:
df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'}, inplace=True)

In [18]:
# create a age group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [21]:
df[['age','age_group']].head()

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

In [25]:
# purchase frequency
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [26]:
df.head(
)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,...,subscription_status,payment_method,shipping_type,discount_applied,promo_code_used,previous_purchases,preferred_payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged,365

In [27]:
df[['discount_applied','promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [28]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [29]:
df.drop('promo_code_used', axis=1)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,payment_method,shipping_type,discount_applied,previous_purchases,preferred_payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,Cash,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,PayPal,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Credit Card,Standard,No,24,Venmo,Quarterly,Middle-aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,PayPal,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Bank Transfer,Store Pickup,No,33,Venmo,Quarterly,Middle-aged,90

In [32]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.0.0-cp38-cp38-win_amd64.whl.metadata (2.0 kB)
Downloading mysql_connector_python-9.0.0-cp38-cp38-win_amd64.whl (14.3 MB)
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.3 MB ? eta -:--:--
    --------------------------------------- 0.3/14.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/14.3 MB 1.5 MB/s eta 0:00:09
   -- ------------------------------------- 1.0/14.3 MB 1.8 MB/s eta 0:00:08
   ---- ----------------------------------- 1.6/14.3 MB 1.9 MB/s eta 0:00:07
   ----- ---------------------------------- 1.8/14.3 MB 1.7 MB/s eta 0:00:08
   ------ --------------------------------- 2.4/14.3 MB 1.8 MB/s eta 0:00:07
   -------- ------------------------------- 2.9/14.3 MB 2.0 MB/s eta 0:00:06
   --------- ------------------------------ 3.4/14.3 MB 2.0 MB/s eta 0:00:06
   ---------- ----------------------------- 3.9/14.3 MB 2.1 MB/s eta 0:00:05
   ----------- ---------------------------- 4.2/14.3 MB 2.2 MB/s eta 0:00:05
   ----------- ---------------------------- 4.2/14.3 MB 2.2 MB/s eta 0:00:05
   -------------- ------------------------- 5.2/14.3 MB 2.1 MB/s eta 0:00:05
   --------------- ------------------------ 5.5/14.3 MB 2.0 MB/s eta 0:00:05
   ---------------- ----------------------- 6.0/14.3 MB 2.1 MB/s eta 0:00:04
   ------------------ --------------------- 6.6/14.3 MB 2.1 MB/s eta 0:00:04
   ------------------- -------------------- 6.8/14.3 MB 2.0 MB/s eta 0:00:04
   ------------------- -------------------- 7.1/14.3 MB 2.0 MB/s eta 0:00:04
   --------------------- ------------------ 7.6/14.3 MB 2.0 MB/s eta 0:00:04
   --------------------- ------------------ 7.9/14.3 MB 2.0 MB/s eta 0:00:04
   ----------------------- ---------------- 8.4/14.3 MB 2.0 MB/s eta 0:00:03
   ------------------------ --------------- 8.7/14.3 MB 2.0 MB/s eta 0:00:03
   -------------------------- ------------- 9.4/14.3 MB 2.1 MB/s eta 0:00:03
   --------------------------- ------------ 9.7/14.3 MB 2.0 MB/s eta 0:00:03
   ---------------------------- ----------- 10.2/14.3 MB 2.0 MB/s eta 0:00:03
   -------------------------------- ------- 11.5/14.3 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 12.3/14.3 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 12.8/14.3 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 13.6/14.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  14.2/14.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 14.3/14.3 MB 2.4 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.0.0

In [33]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp38-cp38-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\megavarnan\appdata\roaming\python\python38\site-packages (from sqlalchemy) (4.13.2)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.1.1-cp38-cp38-win_amd64.whl.metadata (3.9 kB)
Downloading sqlalchemy-2.0.51-cp38-cp38-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.2 MB 4.2 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.2 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 3.4 MB/s eta 0:00:00
Downloading greenlet-3.1.1-cp38-cp38-win_amd64.whl (298 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.1.1 sqlalchemy-2.0.51

In [34]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [43]:
import mysql.connector as mc
from sqlalchemy import create_engine
from urllib.parse import quote_plus

conn = mc.connect(
    user="root",
    password="Mega@2005",
    host="localhost",
    port=3306,
    database="customer_behaviour"
)

password=quote_plus("Mega@2005")

engine = create_engine(f"mysql+pymysql://root:{password}@{conn._host}:{conn._port}/{conn._database}")

df.to_sql(
    name='customers',
    con=engine,
    if_exists='replace',
    index=False
)

print("Data inserted into MySQL database successfully.")

Data inserted into MySQL database successfully.